### ISSUE TITLE
Dataframe HTML tags showing up in exported README

### ISSUE THREAD

**Issue by rxavier** [fastai/nbdev#1155]
Related to https://github.com/fastai/nbdev/issues/474

Rendered readme on Github: https://github.com/rxavier/poniard/blob/develop/README.md
index.ipynb: https://github.com/rxavier/poniard/blob/develop/nbs/index.ipynb

Basically, "raw output" dataframes (for example, when a method simply returns a dataframe, like `get_results` in this example) get this added before the actual table in markdown:

```
<style scoped> .dataframe tbody tr th:only-of-type { vertical-align: middle; }
.dataframe tbody tr th {
    vertical-align: top;
}

.dataframe thead th {
    text-align: right;
}
</style>
```

Meanwhile, dataframes rendered with `display(HTML(df.to_html()))` (which shows after `setup` in this example) display fine.

**Comment by seeM** [comment]
Is this still an issue? I can't find the `<style>` tags in your current README.md

**Comment by rxavier** [comment]
Yeah, it is. I implemented an ugly fix with directives and ipython display.

I should probably fix the issue so the urls point to an earlier version.

**Comment by Attol8** [comment]
Hey I have this same issue on the readme of this [project](https://github.com/Attol8/istatapi) which is generated from the notebook in `nbs/index.ipynb`. The issue is that when I print a dataframe, the HTML tags for the style do show up in the readme. 

Did you have any success in fixing this? I can still see the tags in your readme @rxavier

**Comment by Attol8** [comment]
@rxavier-ml  understood thanks! Fixed the issue with your method, I believe it should be the default for nbdev readmes
